### ISSUE TITLE
`block in check_directories': true does not exist (ArgumentError)

### ISSUE THREAD

**Issue by lsolesen** [chabad360/htmlproofer#13]
```
Run chabad360/htmlproofer@master
  with:
    directory: ./_site
    arguments: --only-4xx true
  --ignore-status-codes "400,403,409,4[2](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:2)9"
  --ignore-empty-alt true
  --ignore-urls "/bjsm.bmj.com/"
  --cache '{ "timeframe": { "external": "[3](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:3)0d" } }'
  
  env:
    RUBY_VERSION: 3.1.2
    BUNDLER_VERSION: 2.3.21
/usr/bin/docker run --name ghcriochabad360htmlproofer_c790a5 --label 290506 --workdir /github/workspace --rm -e "RUBY_VERSION" -e "BUNDLER_VERSION" -e "INPUT_DIRECTORY" -e "INPUT_ARGUMENTS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoint.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/motionsplan-dk-jekyll/motionsplan-dk-jekyll":"/github/workspace" ghcr.io/chabad360/htmlproofer
5.0.2
/usr/local/bundle/gems/html-proofer-5.0.2/lib/html_proofer.rb:[4](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:4)[5](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:5):in `block in check_directories': true does not exist (ArgumentError)
	from /usr/local/bundle/gems/html-proofer-5.0.2/lib/html_proofer.rb:44:in `each'
	from /usr/local/bundle/gems/html-proofer-5.0.2/lib/html_proofer.rb:44:in `check_directories'
	from /usr/local/bundle/gems/html-proofer-5.0.2/lib/html_proofer/cli.rb:22:in `run'
	from /usr/local/bundle/gems/html-proofer-5.0.2/exe/htmlproofer:14:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.1.0/benchmark.rb:3[11](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:11):in `realtime'
	from /usr/local/bundle/gems/html-proofer-5.0.2/exe/htmlproofer:[14](https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283#step:5:15):in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:25:in `load'
	from /usr/local/bundle/bin/htmlproofer:25:in `<main>'
```

Check my repository on: https://github.com/motionsplan/motionsplan-dk-jekyll/actions/runs/3586970550/jobs/6037009283

**Comment by chabad360** [comment]
sorry for the delayed reply, are you still experiencing this issue?

**Comment by lsolesen** [comment]
@chabad360 Yes. I still experience this. Any how to remedy this?

**Comment by chabad360** [comment]
Honestly, no. I don't currently use the action much, but considering the fact that no one else is +1ing this issue I don't think it has something to do with the action itself. You might want to clone the repository locally and test it directly with htmlproofer and see what happens.
